---
dg_macos_rom_root: "{{ ansible_facts['user_dir'] }}/Games/roms"
dg_macos_esde_home: "{{ ansible_facts['user_dir'] }}/ES-DE"
dg_macos_rom_paths: {}
dg_macos_create_rom_dirs: false
dg_macos_systems:
  - name: "gc"
    fullname: "Nintendo GameCube"
    extension: ".ciso .CISO .dff .DFF .dol .DOL .elf .ELF .gcm .GCM .gcz .GCZ .iso .ISO .json .JSON .m3u .M3U .rvz .RVZ .tgc .TGC .wad .WAD .wbfs .WBFS .wia .WIA .7z .7Z .zip .ZIP"
    label: "Dolphin (Standalone)"
    command: "%EMULATOR_DOLPHIN% -b -e %ROM%"
  - name: "ps2"
    fullname: "Sony PlayStation 2"
    extension: ".bin .BIN .chd .CHD .ciso .CISO .cso .CSO .dump .DUMP .elf .ELF .gz .GZ .m3u .M3U .mdf .MDF .img .IMG .iso .ISO .isz .ISZ .ngr .NRG .zso .ZSO"
    label: "PCSX2 (Standalone)"
    command: "%EMULATOR_PCSX2% -batch %ROM%"
  - name: "psp"
    fullname: "Sony PlayStation Portable"
    extension: ".chd .CHD .cso .CSO .elf .ELF .iso .ISO .pbp .PBP .prx .PRX .7z .7Z .zip .ZIP"
    label: "PPSSPP (Standalone)"
    command: "%EMULATOR_PPSSPP% %ROM%"
  - name: "wii"
    fullname: "Nintendo Wii"
    extension: ".ciso .CISO .dff .DFF .dol .DOL .elf .ELF .gcm .GCM .gcz .GCZ .iso .ISO .json .JSON .m3u .M3U .rvz .RVZ .tgc .TGC .wad .WAD .wbfs .WBFS .wia .WIA .7z .7Z .zip .ZIP"
    label: "Dolphin (Standalone)"
    command: "%EMULATOR_DOLPHIN% -b -e %ROM%"
  - name: "atari2600"
    fullname: "Atari 2600"
    extension: ".a26 .bin .A26 .BIN"
    label: "RetroArch (stella)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/stella_libretro.dylib\" %ROM%"
  - name: "atari2600homebrew"
    fullname: "Atari 2600 Homebrew"
    extension: ".a26 .bin .A26 .BIN"
    label: "RetroArch (stella)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/stella_libretro.dylib\" %ROM%"
    platform: atari2600
  - name: "nes"
    fullname: "Nintendo NES"
    extension: ".nes .NES"
    label: "RetroArch (nestopia)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/nestopia_libretro.dylib\" %ROM%"
  - name: "snes"
    fullname: "Super Nintendo"
    extension: ".sfc .smc .SFC .SMC"
    label: "RetroArch (snes9x)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/snes9x_libretro.dylib\" %ROM%"
  - name: "mastersystem"
    fullname: "Sega Master System"
    extension: ".sms .SMS"
    label: "RetroArch (genesis_plus_gx)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/genesis_plus_gx_libretro.dylib\" %ROM%"
  - name: "megadrive"
    fullname: "Sega Mega Drive"
    extension: ".bin .md .smd .BIN .MD .SMD"
    label: "RetroArch (genesis_plus_gx)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/genesis_plus_gx_libretro.dylib\" %ROM%"
  - name: "gba"
    fullname: "Game Boy Advance"
    extension: ".gba .bin .GBA .BIN"
    label: "RetroArch (mgba)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/mgba_libretro.dylib\" %ROM%"
  - name: "gbc"
    fullname: "Game Boy / Color"
    extension: ".gb .gbc .GB .GBC"
    label: "RetroArch (gambatte)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/gambatte_libretro.dylib\" %ROM%"
  - name: "c64"
    fullname: "Commodore 64"
    extension: ".prg .d64 .tap .t64 .crt .PRG .D64 .TAP .T64 .CRT"
    label: "RetroArch (vice_x64sc)"
    command: "%EMULATOR_RETROARCH% --appendconfig \"{{ dg_macos_retroarch_config }}\" -L \"{{ dg_macos_core_dir }}/vice_x64sc_libretro.dylib\" %ROM%"
dg_macos_core_dir: "{{ ansible_facts['user_dir'] }}/Library/Application Support/distrobox-gaming/cores"
dg_macos_retroarch_config: "{{ dg_macos_esde_home }}/retroarch-macos.cfg"
